"""
Run Manifest — the audit spine for a CSO session
The Virtual Biotech

Every run gets a self-describing directory whose MANIFEST.json records, for each
artifact, *what it is, who produced it, and which tool call created it*. This is
what makes a run auditable: the manifest is derived from observed execution, not
from an agent's self-report.

Replaces the flat `web_workspace/{uuid}/` layout, in which every specialist wrote
to one shared directory with names of its own choosing.

Layout::

    runs/<RUN_ID>/                 RUN_ID = YYYYMMDD-HHMMSS-<slug>-<uuid8>
      MANIFEST.json                # this module
      README.md                    # generated by src.utils.run_report
      run.sh                       # replay this run
      inputs/{query.txt,plan.json,config.json}
      work/<agent>/                # per-agent; never flat
        code/scripts/
        data/{raw,processed}/
        results/{figures,tables,reports}/
      evidence/{claims.json,provenance.json}
      logs/{trace.jsonl,cost_report.json,transcript.md}
      report/FINAL_REPORT.md

The `work/<agent>/` sub-layout is fixed so that the skills under
`.claude/skills/single-cell-analysis/`, which already reference
`code/`, `data/processed/` and `results/figures/`, keep working unchanged.

Usage::

    from src.utils.run_manifest import RunManifest

    rm = RunManifest.create(runs_root, query="Safety risks of IL-33 in asthma")
    agent_dir = rm.agent_dir('single-cell-analyst')      # creates the skeleton

    rm.add_artifact(path, produced_by='single-cell-analyst',
                    tool_use_id='toolu_01...', created_by='03_de.py')
    rm.write()

    rm2 = RunManifest.load(rm.run_dir)
    bad = rm2.verify()                                    # re-hash everything
"""

import hashlib
import json
import os
import re
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable, Optional

MANIFEST_VERSION = 1

#: Per-agent sub-layout. Inherited from the retired WorkspaceManager so existing
#: skills that reference these paths keep working.
AGENT_SUBDIRS = (
    "code/scripts",
    "data/raw",
    "data/processed",
    "results/figures",
    "results/tables",
    "results/reports",
)

#: The CSO's own working directory. Leading underscore sorts it above the
#: specialists and marks it as not-a-specialist.
CSO_DIR = "_cso"

#: Files that live in the run root but are bookkeeping, not analysis output.
_NON_ARTIFACT_NAMES = {
    "MANIFEST.json",
    "README.md",
    "run.sh",
    "audit.html",
    "replay_diff.json",
    "environment_full.yml",
}

#: Top-level directories the harness itself owns. Their contents describe the
#: run rather than resulting from it: recording trace.jsonl as an "artifact
#: produced by the CSO" would be circular, and would pad every manifest with
#: files no reviewer wants to audit. An artifact is something an agent produced.
RESERVED_DIRS = {"inputs", "evidence", "logs", "report"}

#: The files the harness actually writes into RESERVED_DIRS. Anything else that
#: turns up there was put there by an agent, and is reported as misplaced rather
#: than dropped — a silently discarded artifact is exactly the kind of gap this
#: manifest exists to close.
_HARNESS_FILES = {
    "inputs/query.txt", "inputs/plan.json", "inputs/config.json",
    "evidence/claims.json", "evidence/provenance.json",
    "logs/trace.jsonl", "logs/cost_report.json", "logs/transcript.md",
    "report/FINAL_REPORT.md",
}

#: Extension → artifact kind. Drives grouping in the README and the UI.
_KIND_BY_SUFFIX = {
    ".png": "figure", ".jpg": "figure", ".jpeg": "figure", ".svg": "figure",
    ".pdf": "figure", ".gif": "figure", ".webp": "figure",
    ".csv": "table", ".tsv": "table", ".parquet": "table", ".xlsx": "table",
    ".py": "code", ".sh": "code", ".ipynb": "code", ".r": "code", ".R": "code",
    ".md": "report", ".txt": "report", ".html": "report",
    ".json": "data", ".jsonl": "data", ".yaml": "data", ".yml": "data",
    ".h5ad": "data", ".h5": "data", ".hdf5": "data", ".npz": "data", ".pkl": "data",
    ".log": "log",
}


def classify(path: Path) -> str:
    """Best-effort artifact kind from the file extension."""
    return _KIND_BY_SUFFIX.get(path.suffix.lower(), "other")


def sha256_file(path: Path, _chunk: int = 1 << 20) -> str:
    """Streaming SHA-256 so large .h5ad files don't land in memory."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(_chunk), b""):
            h.update(block)
    return h.hexdigest()


def slugify(text: str, max_len: int = 32) -> str:
    """Compact, filesystem-safe slug for RUN_IDs — 'IL-33 in asthma' → 'il-33-in-asthma'."""
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return (s[:max_len].rstrip("-")) or "run"


def new_run_id(query: str = "", now: Optional[datetime] = None) -> str:
    """Sortable, human-readable, greppable — unlike the bare UUIDs used before."""
    now = now or datetime.now()
    return f"{now.strftime('%Y%m%d-%H%M%S')}-{slugify(query)}-{uuid.uuid4().hex[:8]}"


class RunManifest:
    """The artifact registry for one run.

    Artifacts are keyed by path relative to the run directory, so a manifest
    stays valid if the run is moved or archived.
    """

    def __init__(self, run_dir: Path, data: dict[str, Any]):
        self.run_dir = Path(run_dir)
        self.data = data

    # ── Construction ─────────────────────────────────────────────────

    @classmethod
    def create(
        cls,
        runs_root: Path,
        query: str = "",
        run_id: Optional[str] = None,
        config: Optional[dict[str, Any]] = None,
    ) -> "RunManifest":
        """Create the run directory skeleton and an empty manifest."""
        run_id = run_id or new_run_id(query)
        run_dir = Path(runs_root) / run_id
        for sub in ("inputs", "work", "evidence", "logs", "report"):
            (run_dir / sub).mkdir(parents=True, exist_ok=True)

        data = {
            "manifest_version": MANIFEST_VERSION,
            "run_id": run_id,
            "created": datetime.now().isoformat(),
            "completed": None,
            "query": query,
            "status": "in_progress",
            "config": config or {},
            "agents": [],
            "artifacts": {},
            "plan": None,
            "execution": [],
        }
        m = cls(run_dir, data)
        m.write()
        return m

    @classmethod
    def load(cls, run_dir: Path) -> "RunManifest":
        run_dir = Path(run_dir)
        with open(run_dir / "MANIFEST.json") as f:
            return cls(run_dir, json.load(f))

    @classmethod
    def load_or_create(cls, runs_root: Path, run_id: str, **kw) -> "RunManifest":
        run_dir = Path(runs_root) / run_id
        if (run_dir / "MANIFEST.json").exists():
            return cls.load(run_dir)
        return cls.create(runs_root, run_id=run_id, **kw)

    # ── Paths ────────────────────────────────────────────────────────

    @property
    def run_id(self) -> str:
        return self.data["run_id"]

    def agent_dir(self, agent: str) -> Path:
        """Per-agent working directory, created with the standard sub-layout."""
        d = self.run_dir / "work" / (agent or CSO_DIR)
        for sub in AGENT_SUBDIRS:
            (d / sub).mkdir(parents=True, exist_ok=True)
        if agent and agent not in self.data["agents"]:
            self.data["agents"].append(agent)
        return d

    def rel(self, path) -> str:
        """Path relative to the run dir, so manifests survive the run being moved."""
        p = Path(path).resolve()
        try:
            return str(p.relative_to(self.run_dir.resolve()))
        except ValueError:
            return str(p)

    # ── Artifacts ────────────────────────────────────────────────────

    def add_artifact(
        self,
        path,
        produced_by: str = CSO_DIR,
        tool_use_id: Optional[str] = None,
        created_by: Optional[str] = None,
        description: Optional[str] = None,
        kind: Optional[str] = None,
        produced_at: Optional[str] = None,
    ) -> Optional[dict[str, Any]]:
        """Register (or update) one artifact. Returns its manifest entry.

        Re-registering a path updates the hash and keeps the earliest
        ``produced_at``, so a file rewritten later in the run is not duplicated.
        """
        p = Path(path)
        if not p.is_file():
            return None

        key = self.rel(p)
        prev = self.data["artifacts"].get(key, {})
        entry = {
            "path": key,
            "kind": kind or classify(p),
            "bytes": p.stat().st_size,
            "sha256": sha256_file(p),
            "produced_by": produced_by or CSO_DIR,
            "produced_at": prev.get("produced_at")
            or produced_at
            or datetime.fromtimestamp(p.stat().st_mtime).isoformat(),
            "modified_at": datetime.fromtimestamp(p.stat().st_mtime).isoformat(),
            "tool_use_id": tool_use_id or prev.get("tool_use_id"),
            "created_by": created_by or prev.get("created_by"),
            "description": description or prev.get("description"),
            # Populated by claims.link_claims_to_manifest() once claims are filed.
            "cited_by": prev.get("cited_by", []),
        }
        self.data["artifacts"][key] = entry
        if entry["produced_by"] not in self.data["agents"] and entry["produced_by"] != CSO_DIR:
            self.data["agents"].append(entry["produced_by"])
        return entry

    def scan(
        self,
        root: Optional[Path] = None,
        produced_by: str = CSO_DIR,
        skip_known: bool = True,
        attribute_by_dir: bool = True,
    ) -> list[dict[str, Any]]:
        """Register every file under *root* not already in the manifest.

        Used as the end-of-run sweep so that anything the PostToolUse hook missed
        (a subprocess writing files directly, say) still lands in the manifest.
        When ``attribute_by_dir`` is set, files under ``work/<agent>/`` are
        credited to that agent, which is the common case.
        """
        root = Path(root) if root else self.run_dir
        added = []
        for p in sorted(root.rglob("*")):
            if not p.is_file() or _is_ignored(p):
                continue
            key = self.rel(p)
            if _in_reserved_dir(key):
                # Harness bookkeeping is not an artifact. Anything *else* here
                # was misplaced by an agent — record that rather than dropping it,
                # so the run README can surface it.
                if key not in _HARNESS_FILES:
                    misplaced = self.data.setdefault("misplaced_files", [])
                    if key not in misplaced:
                        misplaced.append(key)
                continue
            if skip_known and key in self.data["artifacts"]:
                continue
            agent = produced_by
            if attribute_by_dir:
                parts = Path(key).parts
                if len(parts) >= 2 and parts[0] == "work":
                    agent = parts[1]
            e = self.add_artifact(p, produced_by=agent)
            if e:
                added.append(e)
        return added

    def artifacts_by_agent(self) -> dict[str, list[dict[str, Any]]]:
        out: dict[str, list[dict[str, Any]]] = {}
        for e in self.data["artifacts"].values():
            out.setdefault(e["produced_by"], []).append(e)
        for v in out.values():
            v.sort(key=lambda e: (e["kind"], e["path"]))
        return out

    # ── Verification ─────────────────────────────────────────────────

    def verify(self) -> list[dict[str, str]]:
        """Re-hash every artifact. Returns a list of problems; empty means clean.

        This is what makes `run.sh verify` meaningful: it detects an artifact that
        was edited or deleted after the run, which would silently invalidate any
        claim citing it.
        """
        problems = []
        for key, e in sorted(self.data["artifacts"].items()):
            p = self.run_dir / key
            if not p.is_file():
                problems.append({"path": key, "problem": "missing"})
                continue
            actual = sha256_file(p)
            if actual != e.get("sha256"):
                problems.append({
                    "path": key,
                    "problem": "hash_mismatch",
                    "expected": e.get("sha256", ""),
                    "actual": actual,
                })
        return problems

    # ── Execution record ─────────────────────────────────────────────

    def record_execution(self, events: Iterable[dict[str, Any]]) -> None:
        """Store the observed agent dispatch order (from trace agent_start/stop).

        Compared against ``inputs/plan.json`` by src.utils.plan_runner to report
        planned-vs-actual deviations.
        """
        self.data["execution"] = list(events)

    def finalize(self, status: str = "completed") -> None:
        self.data["status"] = status
        self.data["completed"] = datetime.now().isoformat()

    # ── Serialisation ────────────────────────────────────────────────

    def write(self) -> Path:
        path = self.run_dir / "MANIFEST.json"
        tmp = path.with_suffix(".json.tmp")
        with open(tmp, "w") as f:
            json.dump(self.data, f, indent=2, default=str)
        os.replace(tmp, path)   # atomic: a crash mid-write can't truncate the spine
        return path

    def summary(self) -> dict[str, Any]:
        by_kind: dict[str, int] = {}
        total_bytes = 0
        for e in self.data["artifacts"].values():
            by_kind[e["kind"]] = by_kind.get(e["kind"], 0) + 1
            total_bytes += e.get("bytes", 0)
        return {
            "run_id": self.run_id,
            "query": self.data.get("query", ""),
            "status": self.data.get("status"),
            "created": self.data.get("created"),
            "agents": sorted(self.data.get("agents", [])),
            "n_artifacts": len(self.data["artifacts"]),
            "artifacts_by_kind": by_kind,
            "total_bytes": total_bytes,
        }


# ── Directory scanning helpers ───────────────────────────────────────

#: Directories that are never analysis output.
_IGNORE_DIRS = {".claude", "__pycache__", ".git", ".ipynb_checkpoints", ".cache"}


def _in_reserved_dir(rel_path: str) -> bool:
    """True when a run-relative path sits under a harness-owned directory."""
    parts = Path(rel_path).parts
    return bool(parts) and parts[0] in RESERVED_DIRS


def _is_ignored(path: Path) -> bool:
    if any(part in _IGNORE_DIRS for part in path.parts):
        return True
    if path.name in _NON_ARTIFACT_NAMES:
        return True
    return path.name.startswith(".")


def snapshot_dir(root: Path) -> dict[str, tuple[float, int]]:
    """Cheap {relpath: (mtime, size)} snapshot for change detection.

    Deliberately avoids hashing — this runs after *every* tool call, so it must
    stay fast even on a run directory holding multi-GB .h5ad files.
    """
    root = Path(root)
    out: dict[str, tuple[float, int]] = {}
    if not root.exists():
        return out
    for p in root.rglob("*"):
        try:
            if not p.is_file() or _is_ignored(p):
                continue
            rel = str(p.relative_to(root))
            if _in_reserved_dir(rel):
                continue
            st = p.stat()
            out[rel] = (st.st_mtime, st.st_size)
        except OSError:
            continue
    return out


def diff_snapshots(
    before: dict[str, tuple[float, int]],
    after: dict[str, tuple[float, int]],
) -> list[str]:
    """Relative paths that appeared or changed between two snapshots."""
    return sorted(k for k, v in after.items() if before.get(k) != v)
